### ISSUE TITLE
Error: Invalid GIF 87a/89a header.

### ISSUE THREAD

**Issue by JuanIrache** [benwiley4000/gif-frames#11]
I'm struggling with an error. It's inside a try-catch clause but the server still crashes. Not sure I'm handling this the right way.

This is my code, intended for converting still image gifs to jpg:

```js
function gifToJpg(url) {
      gifFrames({ url: url, frames: '0'},function (err, frameData) {
        if (err) {
          throw new Error(err);
        } else {
          for (let k in frameData){
            let frame = frameData[k];
              frame.getImage().pipe(fs.createWriteStream(
                url+".jpg"
              ));
          }
          fs.unlinkSync(url);
        }
    });
}
```

Here's the file I'm converting: https://1drv.ms/u/s!ArtE4Qqqvjd5iS44vpvRk_PVUP_g

And this is the error:

> /node_modules/omggif/omggif.js:372
>     throw new Error("Invalid GIF 87a/89a header.");
>           ^
> Error: Invalid GIF 87a/89a header.
>     at new GifReader (/node_modules/omggif/omggif.js:372:11)
>     at handleGIF (/node_modules/get-pixels-frame-info-update/node-pixels.js:50:14)
>     at doParse (/node_modules/get-pixels-frame-info-update/node-pixels.js:120:7)
>     at /node_modules/get-pixels-frame-info-update/node-pixels.js:192:7
>     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

Thanks

**Comment by benwiley4000** [comment]
Sorry, didn't mean to close.

Hey @JuanIrache, is that link you provided the same url argument you are providing to your function? The url needs to be a direct link to a gif file and your link is a OneDrive download page. Not sure how long direct links from OneDrive last but you might be successful right clicking the image, clicking "copy image url", and using that argument?

**Comment by JuanIrache** [comment]
Hi @benwiley4000 No, I uploaded the file to OneDrive to share it here. When I run the app the file is on my server and I use a direct link. Most files work fine. I just encountered the problem with this one, but the main problem is that I can't catch the error and stop the site from crashing.

**Comment by benwiley4000** [comment]
Ah, I see. Thanks for clarifying. I can't speak to why the particular GIF doesn't work (maybe an omggif problem), but I can try to look into making it possible to catch that error. Thank you for flagging!

**Comment by JuanIrache** [comment]
Yes. That'd be great. I don't mind about that particular GIF. Thanks

**Comment by benwiley4000** [comment]
OK I looked through all the source code and I think I get your problem now.

I assume your calling code looks like this?

```js
try {
  gifToJpg(url);
} catch(err) {
  doSomethingWith(err);
}
```

The problem is that the error occurs and gets thrown asynchronously, so you're always going to crash your server by throwing an error on line 4 of your function. Instead of throwing the error, maybe you can log it? Or have a second error callback argument to `gifToJpg`?

**Comment by JuanIrache** [comment]
Thanks.

In my first post I mistakenly posted my code with the **throw New Error** (line 4) although I knew that was wrong. The error happens also if I just log it. The calling code is rather like this:

```
try {
  await gifToJpg(url);
} catch(err) {
  doSomethingWith(err);
}
```

I assumed the **await** would allow me to catch the error inside the try-catch structure, but I might be wrong.

**Comment by JuanIrache** [comment]
Awaiting directly on gifFrames allowed to catch the error. Thanks. I need to refresh my knowledge of promises.

I assumed my gifToJpg function would return the promise gifFrames creates.

**Comment by benwiley4000** [comment]
I've definitely made that same mistake before! Promises are a bit tricky. You have to pass stuff around pretty explicitly.

**Comment by benwiley4000** [comment]
I think maybe your misunderstanding is that because you expected that calling `await` means that any promise that is created inside the called function will settle before your `await` is finished. Really, `await` only waits for the completion of the promise that is returned from the function it calls. If no promise is returned, it finishes immediately, so probably not what you were expecting.

```js
async function await1() {
  function timeout() {
    new Promise(resolve => setTimeout(resolve, 1000));
  }
  // this await finishes immediately because timeout()
  // doesn't return a promise (although it does create one)
  await timeout();
}

async function await2() {
  function timeout() {
    return new Promise(resolve => setTimeout(resolve, 1000));
  }
  // this await finishes after 1 second because timeout()
  // returns a promise that waits on the setTimeout
  await timeout();
}
```

IMO JavaScript should emit a warning if you `await` a function that doesn't return a Promise. Way too error-prone, as you've seen.

**Comment by JuanIrache** [comment]
Yes, that was it. Thanks for you help and explanations :)
