### ISSUE TITLE
Can the same be done for WebP?

### ISSUE THREAD

**Issue by myeongwooni** [benwiley4000/gif-frames#30]
I want to split webp image in frames ;((

**Comment by benwiley4000** [comment]
I'm not sure how easy it would be. This library uses [get pixels](https://github.com/scijs/get-pixels) which does not support webp, but [webp-convertor](https://github.com/scionoftech/webp-converter) seems like it could be able to help. If you'd like to open a pull request I could try to look at it. I've had trouble handling the pull request backlog lately but I will try to get back to it soon.
