### ISSUE TITLE
For gifs larger than 500kb, image data lost in frames

### ISSUE THREAD

**Issue by ankampraveen** [benwiley4000/gif-frames#4]
![giphy 1](https://user-images.githubusercontent.com/25497252/28236768-3a00c76c-68f4-11e7-8f01-9fe4cab6b196.gif)

i am testing with above gif (30 frames), and i have image data only in 2-3 frames, in all other frames image data is lost (only part of image is present)

Below is my code

gifFrames({
					url : "sample.gif",
					frames : 'all',
					outputType : 'canvas'
				}).then(function(frameData) {
                                    for(var i=0; i<frameData.length;i++)
{
					document.body.append(frameData[i].getImage())
}

})

**Comment by benwiley4000** [comment]
Sorry, I accidentally wasn't watching my own repository!

Thanks for reporting - I'll look into this.

**Comment by benwiley4000** [comment]
Hey @ankampraveen do you think your issue is similar to the one reported in #5 and if so does the partial solution I provided there help at all?

**Comment by benwiley4000** [comment]
@ankampraveen would you be able to test the branch `issue/5-missing-pixels` (#6) and let me know if it solves your issue? `npm install && npm run build` should generate the browser files for you.

**Comment by benwiley4000** [comment]
I think this is the same issue as #5 so I'm closing. Feel free to reopen if your issue isn't solved by the version of the code in master (I'll also be releasing a new version later tonight).

**Comment by benwiley4000** [comment]
v0.4.0 released to npm!

**Comment by ankampraveen** [comment]
Sorry, i did not checked your response.
I just tested with the lastest version, i still observe same issue
can you please debug with GIF which i provided ?

**Comment by benwiley4000** [comment]
@ankampraveen I just tested with your cat GIF. It does have the same problem if you run the code from the original post - I should have clarified you need to add a new option.

Adding the new option `cumulative: true` should fix it (for more details [see here](https://github.com/benwiley4000/gif-frames#options)).

**Comment by benwiley4000** [comment]
@ankampraveen I just tested with your cat GIF. It does have the same problem if you run the code from the original post - I should have clarified you need to add a new option.

Adding the new option `cumulative: true` should fix it (for more details [see here](https://github.com/benwiley4000/gif-frames#options)).

I tested your GIF with `cumulative: true` and it worked.

![screenshot from 2018-03-31 10-31-52](https://user-images.githubusercontent.com/13558253/38164216-006fa7fa-34cf-11e8-8ea9-d902f4b2bdd0.png)
