### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by hyenaheartbeats** [benwiley4000/gif-frames#49]
When putting `<script src="https://unpkg.com/gif-frames@1.0.1/gif-frames.js"></script>` into my HTML file, I get the stated error.

**Comment by benwiley4000** [comment]
Weirdly it seems like unpkg must have dropped support for the ?main= query param. You can use this instead:

https://unpkg.com/gif-frames@1.0.1/dist/gif-frames.min.js

Or unminified:

https://unpkg.com/gif-frames@1.0.1/dist/gif-frames.js

Let me know if that works for you.

**Comment by hyenaheartbeats** [comment]
This worked, thank you!
