### ISSUE TITLE
Canvas only show updated pixel of each frame

### ISSUE THREAD

**Issue by kasual1** [benwiley4000/gif-frames#5]
Hey,
when I save every frame into a canvas object each frame only contains those pixels that changed in between two frames. Do you have any advice how to get the whole image with all pixels of the frame?

See the screenshot below:
![screenshot from 2017-12-03 19-46-30](https://user-images.githubusercontent.com/15854132/33528580-392f1026-d863-11e7-8a50-36d8066098e9.png)

**Comment by benwiley4000** [comment]
Could you provide a copy of the gif?

**Comment by kasual1** [comment]
Here you go! It seems like it happens with almost all gif files 
![skateboard](https://user-images.githubusercontent.com/15854132/33537961-fb14f5f6-d8be-11e7-8f06-76a8b4af7047.gif)

**Comment by benwiley4000** [comment]
Thanks for sharing. I was able to reproduce the problem with the GIF you provided.

The GIF decoding relies on get-pixels ([this function](https://github.com/scijs/get-pixels/blob/master/dom-pixels.js#L29)) which in turn relies on the omggif package. I think [this issue](https://github.com/deanm/omggif/issues/15) might be related to the problem you're experiencing. I'm not sure what the real answer is.. the short explanation is that I had nothing to do with the GIF decoder.

Your problem does seem to be a pretty serious issue that would hamper the usefulness of this package. If you find any clues please let me know!

**Comment by benwiley4000** [comment]
@kasual1 

Here's something I hacked together that actually seems to give you what you want. For a given frame you want to render, iterate the [image data](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData) for each frame from the beginning to that frame.

e.g.

```js
var targetFrame = 19;
gifFrames({
  url: 'https://user-images.githubusercontent.com/15854132/33537961-fb14f5f6-d8be-11e7-8f06-76a8b4af7047.gif',
  frames: `0-${targetFrame}`,
  outputType: 'canvas'
}).then(frameData => {
  const baseCanvas = frameData[0].getImage();
  const ctx = baseCanvas.getContext('2d');
  const baseData = ctx.getImageData(0, 0, baseCanvas.width, baseCanvas.height);
  // iterate all subsequent frames and layer non-empty pixels on top
  for (let i = 1; i <= targetFrame; i++) {
    const data = frameData[i]
      .getImage()
      .getContext('2d')
      .getImageData(0, 0, baseCanvas.width, baseCanvas.height);
    for (let j = 0; j < data.length; j += 4) {
      if (data[j] == 0 && data[j + 1] == 0 && data[j + 2] == 0) {
        // assume we don't need to read this pixel
        continue;
      }
      baseData[j] = data[j];
      baseData[j + 1] = data[j + 1];
      baseData[j + 2] = data[j + 2];
      baseData[j + 3] = data[j + 3];
    }
  }
  ctx.putImageData(baseData, 0, 0);
  document.body.appendChild(baseCanvas);
}).catch(console.error.bind(console));
```

**Comment by benwiley4000** [comment]
Note that the solution I gave above actually *doesn't* work (updated the comment).

**Comment by kasual1** [comment]
Thanks @benwiley4000 I will take a look at it :)

**Comment by benwiley4000** [comment]
Hey @kasual1 I actually just updated with a better version. I think if you layer that result on top of a black background you have something *very* close (but also off).

**Comment by benwiley4000** [comment]
<img width="501" alt="screen shot 2017-12-04 at 2 25 14 am" src="https://user-images.githubusercontent.com/13558253/33540747-6e9db97e-d89a-11e7-9fec-8c7496bd0145.png">

**Comment by kasual1** [comment]
Seems like your quick fix works now :) The only thing I changed was the if statement to ignore pixels:

Change this
 ` if (data[j] == 0 && data[j + 1] == 0 && data[j + 2] == 0)`
to 
` if (data[j] == 0 && data[j + 1] == 0 && data[j + 2] == 0) && data[j + 3] == 0)`

I'll quickly do some testing if it works with other gifs too

**Comment by benwiley4000** [comment]
word!

**Comment by benwiley4000** [comment]
If this solution works perhaps it should be enabled via a flag in the module itself?

**Comment by kasual1** [comment]
Yes I think thats probably the best solution! As far as I understood it the "missing pixels" is expected behavior of a gif file, right? So enabling/disabling "missing pixels" via a flag sounds good!
Are you going to implement that? If it helps I can update the documentation as soon as it is ready. (I'm sort of new to github -> I never really contributed to a public project, so I don't want to break anything ;-) )

**Comment by benwiley4000** [comment]
I think I can do that yep! The catch is making sure we have a similar
solution that works on the server side (non-canvas). I haven't even
verified if this is an issue with the Node package.

**Comment by benwiley4000** [comment]
@kasual1 could you test the branch `issue/5-missing-pixels` (#6) and let me know if it works to your satisfaction? `npm install && npm run build` should generate the browser files for you.

**Comment by kasual1** [comment]
@benwiley4000 Yep, awesome. I'll do it as soon as I'm done at work.

**Comment by kasual1** [comment]
Looking good :+1: 
Tested both server side and client side. Works perfectly.
On the client side I only tested with canvas 
On the server side I tested for jpg and png
I also think that "cumulative" is good naming as an option flag!
attached you can find my outputs:

cumulative == true
![screenshot-2017-12-5 gifprinter 1](https://user-images.githubusercontent.com/15854132/33619489-aeb2bb1c-d9e5-11e7-8251-b2dc4fe57f3b.jpg)

cumulative == false
![screenshot-2017-12-5 gifprinter 2](https://user-images.githubusercontent.com/15854132/33619503-b8558c94-d9e5-11e7-9139-f2cf775599c5.jpg)

Great work @benwiley4000 !

**Comment by benwiley4000** [comment]
Great. I'll see if I can publish a new version tonight!

**Comment by benwiley4000** [comment]
master updated, release later.

**Comment by benwiley4000** [comment]
v0.4.0 released to npm!
